name: swipe_mobile_re
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  collection: ^1.19.1
  dio: ^5.9.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.2.1
  flutter_secure_storage: ^10.0.0
  go_router: ^17.1.0
  mobx: ^2.6.0
  socket_io_client: ^3.1.4
  uuid: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/shaders/liquid.frag
